//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetflixApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Customer_ID { get; set; }
        public int Movie_ID { get; set; }
        public Nullable<int> Rating_Point { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
