//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetflixApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int Rental_ID { get; set; }
        public Nullable<int> Rental_Date { get; set; }
        public Nullable<int> Return_Date { get; set; }
        public int Inventory_ID { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
